#!/usr/bin/env python3
# Generate an anti-aliased I8 font atlas (GX-tiled) + glyph metrics for Swiss.
# Mirrors the IPL font convention: one intensity texture, per-glyph texel
# (s0,t0) + advance width, fixed cell height. Intensity = glyph coverage, which
# the existing TEV modulates with the vertex (font) colour.
from PIL import Image, ImageDraw, ImageFont

FONT = "/mnt/skills/examples/canvas-design/canvas-fonts/Outfit-Regular.ttf"
CELL = 32          # cell height in texels (== atlasFontCellHeight)
FONT_PX = 27       # rasterise size
BASELINE = 24      # baseline within the cell
ATLAS_W = 512      # multiple of 8 (I8 tiles are 8x4)
PAD = 1

# Codepoints to include: printable ASCII + the CP1252 punctuation/Latin-1 the
# UI actually uses (… ‘ ’ “ ” • – — ° and accented game-name letters).
codes = list(range(0x20, 0x7F)) + list(range(0xA0, 0x100)) + [0x85,0x91,0x92,0x93,0x94,0x95,0x96,0x97,0xB0]
codes = sorted(set(codes))

def uni(c):
    try:
        return bytes([c]).decode("cp1252")
    except Exception:
        return None

font = ImageFont.truetype(FONT, FONT_PX)

# First pass: measure advances and lay out shelves to compute atlas height.
meta = {}   # code -> (s0, t0, width)
penx, peny = 0, 0
for c in codes:
    ch = uni(c)
    if ch is None:
        continue
    adv = max(1, round(font.getlength(ch)))
    if penx + adv + PAD > ATLAS_W:
        penx = 0
        peny += CELL
    meta[c] = (penx, peny, adv)
    penx += adv + PAD
atlas_h = peny + CELL
atlas_h = (atlas_h + 3) & ~3   # round up to multiple of 4 for I8 tiling

# Second pass: rasterise glyphs into the atlas.
img = Image.new("L", (ATLAS_W, atlas_h), 0)
d = ImageDraw.Draw(img)
for c, (s0, t0, adv) in meta.items():
    ch = uni(c)
    if ch == " ":
        continue
    d.text((s0, t0 + BASELINE), ch, font=font, fill=255, anchor="ls")

img.save("/tmp/mock/atlas_preview.png")

def to_i8_tiled(im):
    W, H = im.size
    px = im.load()
    out = bytearray()
    for ty in range(0, H, 4):
        for tx in range(0, W, 8):
            for row in range(4):
                for col in range(8):
                    out.append(px[tx + col, ty + row])
    return out

texels = to_i8_tiled(img)

LO, HI = 0x20, 0x100
def m(c, i):
    return meta.get(c, (0, 0, 0))[i]

lines = []
lines.append('#include "IPLFontWrite.h"')
lines.append('#ifdef SWISS_ATLAS_FONT')
lines.append('// Generated by buildtools/gen_atlas.py - do not edit by hand.')
lines.append('// Anti-aliased Outfit atlas in GX I8 (tiled) format.')
lines.append(f'const unsigned int atlasFontTexWidth  = {ATLAS_W};')
lines.append(f'const unsigned int atlasFontTexHeight = {atlas_h};')
lines.append(f'const int          atlasFontCellHeight = {CELL};')
lines.append('')
lines.append('const unsigned char atlasFontTexels[] ATTRIBUTE_ALIGN(32) = {')
row = []
for i, b in enumerate(texels):
    row.append(str(b))
    if len(row) == 24:
        lines.append('\t' + ','.join(row) + ',')
        row = []
if row:
    lines.append('\t' + ','.join(row) + ',')
lines.append('};')
lines.append('')
# Metrics tables indexed by (code - 0x20) for codes 0x20..0xFF.
N = HI - LO
s0t = [str(m(c, 0)) for c in range(LO, HI)]
t0t = [str(m(c, 1)) for c in range(LO, HI)]
wt  = [str(m(c, 2)) for c in range(LO, HI)]
def emit_arr(name, vals):
    lines.append(f'static const short {name}[{N}] = {{')
    for i in range(0, N, 24):
        lines.append('\t' + ','.join(vals[i:i+24]) + ',')
    lines.append('};')
emit_arr('g_s0', s0t)
emit_arr('g_t0', t0t)
emit_arr('g_w',  wt)
lines.append('')
lines.append('static int idx(unsigned char c){ return (c >= 0x20 && c < 0x100) ? c - 0x20 : -1; }')
lines.append('int atlasFontGetWidth(unsigned char c){ int i = idx(c); return i < 0 ? g_w[0] : g_w[i]; }')
lines.append('void atlasFontGetTexture(unsigned char c, int *s0, int *t0, int *width){')
lines.append('\tint i = idx(c); if(i < 0) i = 0;')
lines.append('\t*s0 = g_s0[i]; *t0 = g_t0[i]; *width = g_w[i];')
lines.append('}')
lines.append('#endif // SWISS_ATLAS_FONT')

open("/home/user/swiss-gc-tedde/cube/swiss/source/gui/atlas_font.c", "w").write("\n".join(lines) + "\n")
print(f"atlas {ATLAS_W}x{atlas_h} I8, {len(texels)} bytes ({len(texels)//1024}KB), {len(meta)} glyphs")
print("wrote atlas_font.c and atlas_preview.png")
