/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _cheats_h_
#define _cheats_h_
//---------------------------------------------------------------------------------
extern const unsigned char cheatsEmbedded[];
extern const int cheatsEmbedded_size;
//---------------------------------------------------------------------------------
#endif //_cheats_h_
//---------------------------------------------------------------------------------
