/* -----------------------------------------------------------
      IPLFontWrite.h - Font blitter for IPL ROM fonts
	      - by emu_kidid
	   
      Version 1.0 11/11/2009
        - Initial Code
   ----------------------------------------------------------- */

#ifndef IPLFontWrite_H
#define IPLFontWrite_H

#include "FrameBufferMagic.h"
#include "input.h"

#define wait_press_A() ({while((padsButtonsHeld() & PAD_BUTTON_A)){VIDEO_WaitVSync();} while(!(padsButtonsHeld() & PAD_BUTTON_A)){VIDEO_WaitVSync();}})

#define ALIGN_LEFT 0
#define ALIGN_CENTER 1
#define ALIGN_RIGHT 2

// --- Experimental anti-aliased font atlas -----------------------------------
// Uncomment to render UI text with the bundled anti-aliased Outfit atlas
// (generated by buildtools/gen_atlas.py into atlas_font.c) instead of the
// GameCube IPL ROM font. EXPERIMENTAL: this rewrites the core text path and
// has only been verified by inspection - build it and check it on hardware
// (or Dolphin) before relying on it.
//#define SWISS_ATLAS_FONT

#ifdef SWISS_ATLAS_FONT
extern const unsigned char atlasFontTexels[];
extern const unsigned int  atlasFontTexWidth;
extern const unsigned int  atlasFontTexHeight;
extern const int           atlasFontCellHeight;
int  atlasFontGetWidth(unsigned char c);
void atlasFontGetTexture(unsigned char c, int *s0, int *t0, int *width);
#endif

extern GXColor defaultColor;
extern GXColor disabledColor;
extern GXColor deSelectedColor;
extern char txtbuffer[2048];

void init_font(void);
void drawString(int x, int y, const char *string, float scale, int align, GXColor fontColor);
void drawStringWithCaret(int x, int y, const char *string, float scale, int align, GXColor fontColor, int caretPosition, GXColor caretColor);
void drawStringEllipsis(int x, int y, const char *string, float scale, int align, GXColor fontColor, bool rotateVertical, int maxSize);
int GetFontHeight(float scale);
int GetTextSizeInPixels(const char *string);
float GetTextScaleToFitInWidth(const char *string, int width);
float GetTextScaleToFitInWidthWithMax(const char *string, int width, float max);

#endif
