OSSetAlarm              = 0x800000A0;
OSCancelAlarm           = 0x800000A4;
OSUnhandledException    = 0x800000A8;
OSMaskInterrupts        = 0x800000AC;
OSUnmaskInterrupts      = 0x800000B0;
OSResetSystem           = 0x800000B4;
EXILock                 = 0x800000B8;
EXIUnlock               = 0x800000BC;

OSExceptionContext      = 0x800000C0;
OSCurrentContext        = 0x800000D4;
OSFPUContext            = 0x800000D8;

OSExceptionHandlerTable = 0x80003000;
OSInterruptHandlerTable = 0x80003040;
